font:
  normal:
    family: FiraCode Nerd Font
# Colors (Ayu Mirage)
colors:
  # Default colors
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

  # Normal colors
  normal:
    black: '#191E2A'
    red: '#FF3333'
    green: '#BAE67E'
    yellow: '#FFA759'
    blue: '#73D0FF'
    magenta: '#FFD580'
    cyan: '#95E6CB'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F27983'
    green: '#A6CC70'
    yellow: '#FFCC66'
    blue: '#5CCFE6'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
# Key bindings and stuff
# Get `xcwd` from https://github.com/schischi/xcwd
key_bindings:
  - {key: Return, mods: Control|Shift, command:{program: "bash", args:["-c", "~/.config/alacritty/samedirterm.sh"]}}
